apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configMapName }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.global.activeProfile | quote }}
  SPRING_CONFIG_IMPORT: {{ .Values.global.configServerURL | quote }}
  SPRING_CLOUD_KUBERNETES_DISCOVERY_DISCOVERYSERVERURL: {{ .Values.global.discoveryServerURL | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: {{ .Values.global.keyCloakURL | quote }}
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: {{ .Values.global.kafkaBrokerURL | quote }}