apiVersion: v2
name: dev-env
description: A Helm chart for AMD Bank Kubernetes Development Environment
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: amdbank-common
    version: 0.1.0
    repository: file://../../amdbank-common

  - name: configserver
    version: 0.1.0
    repository: file://../../amdbank-services/configserver

  - name: accounts
    version: 0.1.0
    repository: file://../../amdbank-services/accounts

  - name: cards
    version: 0.1.0
    repository: file://../../amdbank-services/cards

  - name: loans
    version: 0.1.0
    repository: file://../../amdbank-services/loans

  - name: gatewayserver
    version: 0.1.0
    repository: file://../../amdbank-services/gatewayserver

  - name: message
    version: 0.1.0
    repository: file://../../amdbank-services/message

  - name: kafka
    version: 1.0.0
    repository: file://../../kafka

  - name: keycloak
    version: 1.0.0
    repository: file://../../keycloak